//! Real CLI processes against an explicitly synthetic wire peer. Malformed
//! broker replies cannot be generated by a healthy daemon. Separate identity
//! E2E tests qualify the same commands against the real daemon and OIDC flow.
#![cfg(unix)]
#[path = "support/response_contract.rs"]
mod response_contract;
#[path = "support/task_receipt_contract.rs"]
mod task_receipt_contract;
use ed25519_dalek::SigningKey;
use opaque_core::attest::{
    AuditPosture, FederationPosture, ReportPayload, TrustDomainPosture, sign_report,
};
use serde_json::{Value, json};
use std::io::{Read, Write};
use std::os::unix::{
    fs::PermissionsExt,
    net::{UnixListener, UnixStream},
};
use std::path::PathBuf;
use std::process::{Command, Output};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

type Reply = Box<dyn FnOnce(&Value) -> Value + Send>;
struct Peer {
    _dir: tempfile::TempDir,
    sock: PathBuf,
    worker: Option<std::thread::JoinHandle<Vec<Value>>>,
    stop: std::sync::Arc<std::sync::atomic::AtomicBool>,
}
fn read_frame(stream: &mut UnixStream) -> Value {
    let mut size = [0; 4];
    stream.read_exact(&mut size).unwrap();
    let size = u32::from_be_bytes(size) as usize;
    assert!(size <= opaque_core::MAX_FRAME_LENGTH);
    let mut frame = vec![0; size];
    stream.read_exact(&mut frame).unwrap();
    serde_json::from_slice(&frame).unwrap()
}
impl Peer {
    fn new(replies: Vec<(&'static str, Reply)>) -> Self {
        let base = std::fs::canonicalize("/tmp").unwrap();
        let dir = tempfile::Builder::new()
            .prefix("oq-cli-")
            .tempdir_in(base)
            .unwrap();
        std::fs::set_permissions(dir.path(), std::fs::Permissions::from_mode(0o700)).unwrap();
        let sock = dir.path().join("daemon.sock");
        let listener = UnixListener::bind(&sock).unwrap();
        std::fs::set_permissions(&sock, std::fs::Permissions::from_mode(0o600)).unwrap();
        std::fs::write(dir.path().join("daemon.token"), "synthetic-wire-token").unwrap();
        listener.set_nonblocking(true).unwrap();
        let stop = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
        let worker_stop = stop.clone();
        let worker = std::thread::spawn(move || {
            let mut requests = Vec::new();
            let mut replies = std::collections::VecDeque::from(replies);
            let mut deadline = Instant::now() + Duration::from_secs(15);
            loop {
                // Keep observing after the last reply, including when no I/O is
                // expected. On shutdown, drain connections queued before the CLI
                // exited rather than returning a count fixed by the reply list.
                let mut stream = match listener.accept() {
                    Ok((stream, _)) => stream,
                    Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                        if worker_stop.load(std::sync::atomic::Ordering::Acquire) {
                            assert!(
                                replies.is_empty(),
                                "CLI ended before every expected request"
                            );
                            break;
                        }
                        assert!(
                            replies.is_empty() || Instant::now() < deadline,
                            "missing CLI request"
                        );
                        std::thread::sleep(Duration::from_millis(5));
                        continue;
                    }
                    Err(e) => panic!("accept: {e}"),
                };
                assert!(
                    requests.len() < 1024,
                    "unbounded unexpected CLI connections"
                );
                let Some((method, reply)) = replies.pop_front() else {
                    // The accepted connection itself violates the no-I/O / no-
                    // replay oracle. Do not wait for a malicious or broken
                    // caller to send a handshake before recording that fact.
                    requests.push(json!({"unexpected_connection": true}));
                    continue;
                };
                stream.set_nonblocking(false).unwrap();
                stream
                    .set_read_timeout(Some(Duration::from_secs(10)))
                    .unwrap();
                stream
                    .set_write_timeout(Some(Duration::from_secs(10)))
                    .unwrap();
                let handshake = read_frame(&mut stream);
                assert_eq!(handshake["handshake"], "v1");
                assert_eq!(handshake["daemon_token"], "synthetic-wire-token");
                let request = read_frame(&mut stream);
                assert_eq!(request["method"], method);
                let response = reply(&request);
                requests.push(request);
                let data = serde_json::to_vec(&response).unwrap();
                stream
                    .write_all(&(data.len() as u32).to_be_bytes())
                    .unwrap();
                stream.write_all(&data).unwrap();
                deadline = Instant::now() + Duration::from_secs(15);
            }
            requests
        });
        Self {
            _dir: dir,
            sock,
            worker: Some(worker),
            stop,
        }
    }
    fn command(&self) -> Command {
        let mut command = Command::new(env!("CARGO_BIN_EXE_opaque"));
        command
            .env_clear()
            .env("HOME", self._dir.path())
            .env("PATH", "/usr/bin:/bin")
            .env("NO_COLOR", "1")
            .env("TERM", "dumb")
            .args(["--socket", self.sock.to_str().unwrap()]);
        // Preserve counters from this actual CLI subprocess after env_clear.
        #[cfg(coverage_nightly)]
        {
            let dir = std::env::var_os("OPAQUE_COVERAGE_PROFILE_DIR").expect("coverage directory");
            let dir = PathBuf::from(dir);
            assert!(dir.is_absolute() && dir.is_dir());
            command.env("LLVM_PROFILE_FILE", dir.join("peer-%p-%m-%c.profraw"));
        }
        command
    }
    fn finish(mut self) -> Vec<Value> {
        self.stop.store(true, std::sync::atomic::Ordering::Release);
        self.worker.take().unwrap().join().unwrap()
    }
}
impl Drop for Peer {
    fn drop(&mut self) {
        if let Some(worker) = self.worker.take() {
            self.stop.store(true, std::sync::atomic::Ordering::Release);
            let _ = worker.join();
        }
    }
}
#[test]
fn synthetic_peer_observes_zero_expected_and_trailing_unexpected_connections() {
    for expected in [false, true] {
        let peer = Peer::new(if expected {
            vec![("ping", result(json!({"status": "ok"})))]
        } else {
            vec![]
        });
        if expected {
            let mut stream = UnixStream::connect(&peer.sock).unwrap();
            stream
                .set_read_timeout(Some(Duration::from_secs(2)))
                .unwrap();
            stream
                .set_write_timeout(Some(Duration::from_secs(2)))
                .unwrap();
            for frame in [
                json!({"handshake":"v1", "daemon_token":"synthetic-wire-token"}),
                json!({"id":1, "method":"ping", "params":null}),
            ] {
                let data = serde_json::to_vec(&frame).unwrap();
                stream
                    .write_all(&(data.len() as u32).to_be_bytes())
                    .unwrap();
                stream.write_all(&data).unwrap();
            }
            assert_eq!(read_frame(&mut stream)["result"]["status"], "ok");
        }
        // Leave this client connected without a frame: finish must notice the
        // queued connection and must not block waiting for its handshake.
        let unexpected = UnixStream::connect(&peer.sock).unwrap();
        let requests = peer.finish();
        assert_eq!(requests.len(), if expected { 2 } else { 1 });
        assert_eq!(
            requests.last().unwrap(),
            &json!({"unexpected_connection":true})
        );
        if expected {
            assert_eq!(requests[0]["method"], "ping");
        }
        drop(unexpected);
    }
}

fn result(value: Value) -> Reply {
    Box::new(move |_| json!({"id":1,"result":value}))
}
fn grant() -> Value {
    json!({"session_id":"test-session", "session_token":"fresh-test-token", "mode":"delegated", "expires_at_utc_ms":1234,"on_behalf_of_label":"fixture human"})
}
fn run(command: &mut Command) -> Output {
    // Files avoid pipe deadlocks; bounded waits reap a broken CLI too.
    let stdout = tempfile::tempfile().unwrap();
    let stderr = tempfile::tempfile().unwrap();
    command
        .stdout(stdout.try_clone().unwrap())
        .stderr(stderr.try_clone().unwrap());
    let mut child = command.spawn().unwrap();
    let deadline = Instant::now() + Duration::from_secs(20);
    let status = loop {
        if let Some(status) = child.try_wait().unwrap() {
            break status;
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            let _ = child.wait();
            panic!("CLI deadline exceeded");
        }
        std::thread::sleep(Duration::from_millis(5));
    };
    use std::io::{Seek, SeekFrom};
    let read = |mut file: std::fs::File| {
        file.seek(SeekFrom::Start(0)).unwrap();
        let mut bytes = Vec::new();
        file.read_to_end(&mut bytes).unwrap();
        bytes
    };
    Output {
        status,
        stdout: read(stdout),
        stderr: read(stderr),
    }
}
fn assert_exit(output: &Output, code: i32) {
    assert_eq!(
        output.status.code(),
        Some(code),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
fn assert_ended(requests: &[Value]) {
    assert_eq!(requests.len(), 2);
    assert_eq!(requests[1]["params"], json!({"session_id":"test-session"}));
}
#[test]
fn agent_environment_exit_status_and_cleanup_are_observed_in_child() {
    for inherit in [false, true] {
        let peer = Peer::new(vec![
            ("agent_session_start", result(grant())),
            (
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ),
        ]);
        let mut command = peer.command();
        command
            .env("PRIVATE_SENTINEL", "must-not-leak")
            .env("EXPLICIT_ALLOWED", "allowed")
            .env("OPAQUE_SESSION_TOKEN", "stale-parent-token")
            .env("OPAQUE_AGENT_SESSION_ID", "stale-id")
            .env("OPAQUE_AGENT_WRAPPED", "stale")
            .env("OPAQUE_SOCK", "/stale/socket")
            .args([
                "--json",
                "agent",
                "run",
                "--ttl-secs",
                "73",
                "--pass-env",
                "EXPLICIT_ALLOWED",
                "--pass-env",
                "ABSENT_OPTIONAL",
            ]);
        if inherit {
            command.arg("--inherit-env");
        }
        command.args(["--", "/bin/sh", "-c", "test \"$EXPLICIT_ALLOWED\" = allowed && test \"$OPAQUE_SESSION_TOKEN\" = fresh-test-token && test \"$OPAQUE_AGENT_SESSION_ID\" = test-session && test \"$OPAQUE_AGENT_WRAPPED\" = 1 && test -S \"$OPAQUE_SOCK\" || exit 90; printf '%s' \"${PRIVATE_SENTINEL-unset}\"; exit 23"]);
        let output = run(&mut command);
        assert_exit(&output, 23);
        assert_eq!(
            String::from_utf8(output.stdout).unwrap(),
            if inherit { "must-not-leak" } else { "unset" }
        );
        let requests = peer.finish();
        assert_ended(&requests);
        assert_eq!(requests[0]["params"]["ttl_secs"], 73);
        assert_eq!(requests[0]["params"]["label"], "/bin/sh");
    }
}
#[test]
fn agent_spawn_and_child_signal_failures_revoke_the_grant() {
    for (args, expected) in [
        (vec!["/definitely/missing/opaque-agent"], 1),
        (vec!["/bin/sh", "-c", "kill -TERM $$"], 128 + libc::SIGTERM),
    ] {
        let peer = Peer::new(vec![
            ("agent_session_start", result(grant())),
            (
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ),
        ]);
        let output = run(peer.command().args(["agent", "run", "--"]).args(args));
        assert_exit(&output, expected);
        assert_ended(&peer.finish());
    }
}
#[test]
fn agent_rejects_malformed_grants_before_child_and_revokes_identifiable_grants() {
    for bad in [
        json!(null),
        json!({}),
        json!({"session_id":""}),
        json!({"session_id":"test-session"}),
        json!({"session_id":"test-session","session_token":"  "}),
    ] {
        let has_id = bad["session_id"] == "test-session";
        let mut replies = vec![("agent_session_start", result(bad))];
        if has_id {
            replies.push((
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ));
        }
        let peer = Peer::new(replies);
        let marker = peer._dir.path().join("must-not-execute");
        let output = run(peer
            .command()
            .args(["--json", "agent", "run", "--", "/usr/bin/touch"])
            .arg(&marker));
        assert_exit(&output, 1);
        assert!(!marker.exists());
        let requests = peer.finish();
        assert_eq!(requests.len(), if has_id { 2 } else { 1 });
    }
}
#[test]
fn autonomous_mode_mismatch_revokes_without_launching_and_success_is_labeled() {
    for correct in [false, true] {
        let mut response = grant();
        if correct {
            response["mode"] = json!("autonomous");
        }
        let peer = Peer::new(vec![
            ("agent_session_start", result(response)),
            (
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ),
        ]);
        let marker = peer._dir.path().join("executed");
        let output = run(peer
            .command()
            .args([
                "agent",
                "run",
                "--mode",
                "autonomous",
                "--service",
                "test-worker",
                "--",
                "/usr/bin/touch",
            ])
            .arg(&marker));
        assert_exit(&output, if correct { 0 } else { 1 });
        assert_eq!(marker.exists(), correct);
        let requests = peer.finish();
        assert_ended(&requests);
        assert_eq!(requests[0]["params"]["service"], "test-worker");
    }
}
#[test]
fn agent_does_not_report_success_if_revocation_is_denied() {
    let peer = Peer::new(vec![
        ("agent_session_start", result(grant())),
        (
            "agent_session_end",
            Box::new(|_| json!({"id":1,"error":{"code":"denied","message":"revocation refused"}})),
        ),
    ]);
    let output = run(peer
        .command()
        .args(["--json", "agent", "run", "--", "/usr/bin/true"]));
    assert_exit(&output, 1);
    assert!(String::from_utf8_lossy(&output.stderr).contains("cleanup failed"));
    assert_ended(&peer.finish());
}
fn key() -> SigningKey {
    SigningKey::from_bytes(&[31; 32])
}
fn key_hex() -> String {
    key()
        .verifying_key()
        .as_bytes()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}
fn payload(request: &Value) -> ReportPayload {
    ReportPayload {
        nonce: request["params"]["nonce"].as_str().unwrap().into(),
        issued_at: SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64,
        daemon_version: "fixture".into(),
        uid: 42,
        trust_domain: TrustDomainPosture {
            enforce: true,
            custody_ok: true,
            custody_violations: vec![],
        },
        audit: AuditPosture {
            chain_ok: true,
            records: 3,
            detail: None,
        },
        federation: None,
        factors: vec![],
    }
}
fn attestation(mutation: &'static str) -> Reply {
    Box::new(move |request| {
        let mut payload = payload(request);
        match mutation {
            "nonce" => payload.nonce = "00".repeat(16),
            "stale" => payload.issued_at -= 1000,
            "future" => payload.issued_at += 1000,
            "custody" => {
                payload.trust_domain.custody_ok = false;
                payload
                    .trust_domain
                    .custody_violations
                    .push("fixture custody violation".into());
            }
            "audit" => {
                payload.audit.chain_ok = false;
                payload.audit.detail = Some("fixture broken chain".into());
            }
            "session" => payload.trust_domain.enforce = false,
            "federation" => {
                payload.federation = Some(FederationPosture {
                    org: "fixture".into(),
                    version: 2,
                    digest: "é".repeat(20),
                });
                payload.factors.push("test factor".into());
            }
            _ => {}
        }
        let signer = if mutation == "signature" {
            SigningKey::from_bytes(&[32; 32])
        } else {
            key()
        };
        let mut response =
            json!({"report":sign_report(&payload,&signer).unwrap(),"attestation_key":key_hex()});
        match mutation {
            "key" => response["attestation_key"] = json!("invalid"),
            "report" => response["report"] = json!("malformed"),
            "missing_report" => {
                response.as_object_mut().unwrap().remove("report");
            }
            "missing_key" => {
                response.as_object_mut().unwrap().remove("attestation_key");
            }
            "missing_result" => return json!({"id":1}),
            _ => {}
        }
        json!({"id":1,"result":response})
    })
}
#[test]
fn attestation_json_verifies_signature_pin_nonce_and_freshness_before_success() {
    for mutation in [
        "valid",
        "nonce",
        "stale",
        "future",
        "signature",
        "report",
        "missing_report",
        "missing_key",
        "missing_result",
        "pin",
        "key",
    ] {
        let peer = Peer::new(vec![("attestation_report", attestation(mutation))]);
        let mut command = peer.command();
        command.args(["--json", "attest"]);
        if mutation != "key" {
            command.args([
                "--key",
                &if mutation == "pin" {
                    "00".repeat(32)
                } else {
                    key_hex().to_uppercase()
                },
            ]);
        }
        let output = run(&mut command);
        assert_exit(&output, if mutation == "valid" { 0 } else { 3 });
        let verdict: Value = serde_json::from_slice(&output.stdout).unwrap();
        if mutation == "missing_result" {
            assert!(verdict.get("verified").is_none());
            assert!(
                verdict["error"]
                    .as_str()
                    .unwrap()
                    .contains("invalid daemon response envelope")
            );
        } else {
            assert_eq!(
                verdict["verified"],
                mutation == "valid",
                "{mutation}: {verdict}"
            );
        }
        if mutation == "valid" {
            assert_eq!(verdict["key_pinned"], true);
            assert_eq!(verdict["release_eligible"], true);
        } else {
            assert!(verdict.get("payload").is_none());
            assert!(verdict.get("report").is_none());
        }
        let requests = peer.finish();
        let nonce = requests[0]["params"]["nonce"].as_str().unwrap();
        assert_eq!(nonce.len(), 32);
        assert!(nonce.bytes().all(|b| b.is_ascii_hexdigit()));
    }
}
#[test]
fn attestation_health_and_release_eligibility_have_distinct_exit_and_output_contracts() {
    for mutation in ["valid", "session", "custody", "audit", "federation"] {
        for json_mode in [false, true] {
            let peer = Peer::new(vec![("attestation_report", attestation(mutation))]);
            let mut command = peer.command();
            if json_mode {
                command.arg("--json");
            }
            command.args(["attest", "--raw"]);
            let output = run(&mut command);
            let healthy = !matches!(mutation, "custody" | "audit");
            assert_exit(&output, if healthy { 0 } else { 3 });
            if json_mode {
                let verdict: Value = serde_json::from_slice(&output.stdout).unwrap();
                assert_eq!(verdict["verified"], true);
                assert_eq!(verdict["key_pinned"], false);
                assert_eq!(verdict["healthy"], healthy);
                assert_eq!(
                    verdict["release_eligible"],
                    healthy && mutation != "session"
                );
            } else {
                let stdout = String::from_utf8_lossy(&output.stdout);
                assert!(stdout.contains("opqa1."));
                assert!(String::from_utf8_lossy(&output.stderr).contains("Key not pinned"));
                if mutation == "session" {
                    assert!(stdout.contains("not eligible"));
                }
                if mutation == "custody" {
                    assert!(stdout.contains("fixture custody violation"));
                }
                if mutation == "audit" {
                    assert!(stdout.contains("fixture broken chain"));
                }
            }
            peer.finish();
        }
    }
}

#[test]
fn agent_rejects_wrong_or_missing_revocation_acknowledgments() {
    for acknowledgment in [
        json!({}),
        json!({"status":"ended","session_id":"other-session"}),
        json!({"status":"active","session_id":"test-session"}),
    ] {
        let peer = Peer::new(vec![
            ("agent_session_start", result(grant())),
            ("agent_session_end", result(acknowledgment)),
        ]);
        let output = run(peer
            .command()
            .args(["--json", "agent", "run", "--", "/usr/bin/true"]));
        assert_exit(&output, 1);
        assert!(String::from_utf8_lossy(&output.stderr).contains("did not acknowledge"));
        assert_ended(&peer.finish());
    }
}

#[test]
fn human_attestation_output_never_renders_invalid_evidence_as_verified() {
    for mutation in ["signature", "pin"] {
        let peer = Peer::new(vec![("attestation_report", attestation(mutation))]);
        let pin = if mutation == "pin" {
            "00".repeat(32)
        } else {
            key_hex()
        };
        let output = run(peer.command().args(["attest", "--raw", "--key", &pin]));
        assert_exit(&output, 3);
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(!stdout.contains("opqa1."));
        assert!(!stdout.contains("posture healthy"));
        assert!(
            String::from_utf8_lossy(&output.stderr).contains(if mutation == "pin" {
                "KEY MISMATCH"
            } else {
                "VERIFICATION FAILED"
            })
        );
        peer.finish();
    }
}

#[test]
fn agent_with_noncontrolling_terminal_descriptor_owns_its_process_group() {
    use std::os::fd::FromRawFd;
    use std::os::unix::process::CommandExt;
    let (mut master, mut slave) = (-1, -1);
    // An owned PTY exercises terminal detection without touching the user's
    // terminal or creating a login session. All descriptors are RAII-owned.
    assert_eq!(
        unsafe {
            libc::openpty(
                &mut master,
                &mut slave,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
            )
        },
        0
    );
    let _master = unsafe { std::fs::File::from_raw_fd(master) };
    let slave = unsafe { std::fs::File::from_raw_fd(slave) };
    let peer = Peer::new(vec![
        ("agent_session_start", result(grant())),
        (
            "agent_session_end",
            result(json!({"status":"ended","session_id":"test-session"})),
        ),
    ]);
    let mut command = peer.command();
    command.process_group(0).stdin(slave).args([
        "--json",
        "agent",
        "run",
        "--",
        "/bin/sh",
        "-c",
        "test \"$(ps -o pgid= -p $$ | tr -d ' ')\" = \"$$\"",
    ]);
    assert_exit(&run(&mut command), 0);
    assert_ended(&peer.finish());
}

fn assert_cancelled_group(script: &str, signal: i32) {
    let peer = Peer::new(vec![
        ("agent_session_start", result(grant())),
        (
            "agent_session_end",
            result(json!({"status":"ended","session_id":"test-session"})),
        ),
    ]);
    let marker = peer._dir.path().join("descendant.pid");
    // The grandchild writes readiness only after installing its ignored TERM.
    // Its inherited stdout also witnesses process cleanup: EOF cannot occur
    // while that live descendant still owns the pipe, even if its leader exits.
    let mut wrapper = peer
        .command()
        .args([
            "--json",
            "agent",
            "run",
            "--",
            "/bin/sh",
            "-c",
            script,
            "opaque-leader",
        ])
        .arg(&marker)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .unwrap();
    struct Cleanup {
        wrapper: std::process::Child,
        marker: PathBuf,
    }
    impl Drop for Cleanup {
        fn drop(&mut self) {
            if let Ok(pid) = std::fs::read_to_string(&self.marker)
                .and_then(|s| s.trim().parse::<i32>().map_err(std::io::Error::other))
            {
                let group = unsafe { libc::getpgid(pid) };
                if group > 0 && group != unsafe { libc::getpgrp() } {
                    unsafe {
                        libc::kill(-group, libc::SIGKILL);
                    }
                }
            }
            let _ = self.wrapper.kill();
            let _ = self.wrapper.wait();
        }
    }
    let stdout = wrapper.stdout.take().unwrap();
    let mut cleanup = Cleanup {
        wrapper,
        marker: marker.clone(),
    };
    let deadline = Instant::now() + Duration::from_secs(10);
    while !marker.is_file() {
        assert!(cleanup.wrapper.try_wait().unwrap().is_none());
        assert!(Instant::now() < deadline, "grandchild readiness deadline");
        std::thread::sleep(Duration::from_millis(5));
    }
    let (send, receive) = std::sync::mpsc::channel();
    let reader = std::thread::spawn(move || {
        let mut stdout = stdout;
        let mut bytes = Vec::new();
        let result = stdout.read_to_end(&mut bytes);
        let _ = send.send(result);
    });
    assert_eq!(
        unsafe { libc::kill(cleanup.wrapper.id() as i32, signal) },
        0
    );
    let deadline = Instant::now() + Duration::from_secs(10);
    let status = loop {
        if let Some(status) = cleanup.wrapper.try_wait().unwrap() {
            break status;
        }
        assert!(Instant::now() < deadline, "wrapper cancellation deadline");
        std::thread::sleep(Duration::from_millis(5));
    };
    assert_eq!(status.code(), Some(128 + signal));
    // Generous: reaping the group and draining the pipe can lag well past a
    // few seconds under a saturated parallel test run. This still fails when a
    // descendant genuinely leaks stdout, only later.
    let closed = receive.recv_timeout(Duration::from_secs(30));
    // Cleanup first, including assertion-failure paths, so the reader cannot
    // leave an owned process behind if this regression returns.
    drop(cleanup);
    reader.join().unwrap();
    assert!(
        closed.is_ok_and(|r| r.is_ok()),
        "descendant kept inherited stdout open after wrapper exit"
    );
    assert_ended(&peer.finish());
}

#[test]
fn agent_termination_reaps_a_group_when_its_leader_exits_before_a_stubborn_descendant() {
    let script = "trap 'exit 0' TERM; /bin/sh -c 'trap \"\" TERM INT; echo $$ > \"$1.tmp\"; /bin/mv \"$1.tmp\" \"$1\"; while :; do /bin/sleep 1; done' opaque-descendant \"$1\" & wait";
    assert_cancelled_group(script, libc::SIGTERM);
}

#[test]
fn agent_interrupt_escalates_and_reaps_a_group_that_ignores_signals() {
    let script = "trap \"\" INT TERM; echo $$ > \"$1.tmp\"; /bin/mv \"$1.tmp\" \"$1\"; while :; do /bin/sleep 1; done";
    assert_cancelled_group(script, libc::SIGINT);
}

#[test]
fn agent_cancellation_reaps_a_direct_child_that_leaves_its_owned_group() {
    use std::os::unix::process::CommandExt;
    use std::process::{Child, Stdio};

    struct Cleanup {
        wrapper: Child,
        sentinel: Option<Child>,
        sentinel_reaped: bool,
    }
    impl Drop for Cleanup {
        fn drop(&mut self) {
            let group = self.wrapper.id() as i32;
            // Only teardown signals this wholly owned group. Its unreaped
            // sentinel fences reuse even if the child failed before publishing
            // readiness. Normal-path assertions verify the sentinel beforehand.
            if let Some(sentinel) = &self.sentinel
                && !self.sentinel_reaped
                && unsafe { libc::getpgid(sentinel.id() as i32) } == group
                && group != unsafe { libc::getpgrp() }
            {
                unsafe { libc::kill(-group, libc::SIGKILL) };
            }
            let _ = self.wrapper.kill();
            let _ = self.wrapper.wait();
            if let Some(sentinel) = &mut self.sentinel {
                let _ = sentinel.kill();
                let _ = sentinel.wait();
            }
        }
    }

    for signal in [libc::SIGINT, libc::SIGTERM] {
        let (release, grant_ready) = std::sync::mpsc::channel();
        let peer = Peer::new(vec![
            (
                "agent_session_start",
                Box::new(move |_| {
                    grant_ready.recv_timeout(Duration::from_secs(15)).unwrap();
                    json!({"id":1,"result":grant()})
                }),
            ),
            (
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ),
        ]);
        let marker = peer._dir.path().join("moved-child.json");
        let script = r#"
import json, os, pathlib, signal, sys
signal.signal(signal.SIGINT, signal.SIG_IGN)
signal.signal(signal.SIGTERM, signal.SIG_IGN)
original = os.getpgrp()
wrapper_group = os.getpgid(os.getppid())
os.setpgid(0, wrapper_group)
path = pathlib.Path(sys.argv[1])
temporary = path.with_suffix('.tmp')
temporary.write_text(json.dumps({'pid':os.getpid(), 'original':original, 'joined':os.getpgrp()}))
temporary.replace(path)
while True:
    signal.pause()
"#;
        let stdout = tempfile::tempfile().unwrap();
        let stderr = tempfile::tempfile().unwrap();
        let wrapper = peer
            .command()
            .process_group(0)
            .args([
                "--json",
                "agent",
                "run",
                "--",
                "/usr/bin/python3",
                "-c",
                script,
            ])
            .arg(&marker)
            .stdin(Stdio::null())
            .stdout(stdout.try_clone().unwrap())
            .stderr(stderr.try_clone().unwrap())
            .spawn()
            .unwrap();
        let mut cleanup = Cleanup {
            wrapper,
            sentinel: None,
            sentinel_reaped: false,
        };
        let wrapper_group = cleanup.wrapper.id() as i32;
        assert_ne!(wrapper_group, unsafe { libc::getpgrp() });
        cleanup.sentinel = Some(
            Command::new("/bin/sleep")
                .arg("60")
                .process_group(wrapper_group)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .spawn()
                .unwrap(),
        );
        // No direct child can launch before teardown owns its group sentinel.
        release.send(()).unwrap();
        let deadline = Instant::now() + Duration::from_secs(10);
        while !marker.is_file() {
            assert!(Instant::now() < deadline, "moved child readiness deadline");
            std::thread::sleep(Duration::from_millis(5));
        }
        let observed: Value = serde_json::from_slice(&std::fs::read(&marker).unwrap()).unwrap();
        let pid = observed["pid"].as_i64().unwrap() as i32;
        assert_eq!(observed["original"], pid);
        assert_eq!(observed["joined"], wrapper_group);
        assert_ne!(pid, wrapper_group);
        assert_eq!(unsafe { libc::getpgid(pid) }, wrapper_group);
        assert_eq!(unsafe { libc::kill(wrapper_group, signal) }, 0);
        let deadline = Instant::now() + Duration::from_secs(10);
        let status = loop {
            if let Some(status) = cleanup.wrapper.try_wait().unwrap() {
                break status;
            }
            assert!(
                Instant::now() < deadline,
                "moved child cancellation deadline"
            );
            std::thread::sleep(Duration::from_millis(5));
        };
        assert_eq!(status.code(), Some(128 + signal));
        assert_eq!(unsafe { libc::kill(pid, 0) }, -1, "direct child survived");
        assert_eq!(
            std::io::Error::last_os_error().raw_os_error(),
            Some(libc::ESRCH)
        );
        let sentinel_status = cleanup.sentinel.as_mut().unwrap().try_wait().unwrap();
        cleanup.sentinel_reaped = sentinel_status.is_some();
        assert!(sentinel_status.is_none());
        assert_ended(&peer.finish());
    }
}

#[test]
fn agent_cancellation_during_pending_grant_revokes_without_spawning() {
    for signal in [libc::SIGTERM, libc::SIGINT] {
        let (arrived_send, arrived_receive) = std::sync::mpsc::sync_channel(0);
        let (release_send, release_receive) = std::sync::mpsc::sync_channel(0);
        let peer = Peer::new(vec![
            (
                "agent_session_start",
                Box::new(move |_| {
                    // The request has arrived, but the broker has not sent a
                    // grant. Only the test's explicit release can advance it.
                    arrived_send.send(()).unwrap();
                    release_receive
                        .recv_timeout(Duration::from_secs(15))
                        .unwrap();
                    json!({"id":1,"result":grant()})
                }),
            ),
            (
                "agent_session_end",
                result(json!({"status":"ended","session_id":"test-session"})),
            ),
        ]);
        let marker = peer._dir.path().join("cancelled-child-must-not-execute");
        let stdout = tempfile::tempfile().unwrap();
        let stderr = tempfile::tempfile().unwrap();
        let wrapper = peer
            .command()
            .args(["--json", "agent", "run", "--", "/usr/bin/touch"])
            .arg(&marker)
            .stdin(std::process::Stdio::null())
            .stdout(stdout.try_clone().unwrap())
            .stderr(stderr.try_clone().unwrap())
            .spawn()
            .unwrap();
        struct Cleanup(std::process::Child);
        impl Drop for Cleanup {
            fn drop(&mut self) {
                let _ = self.0.kill();
                let _ = self.0.wait();
            }
        }
        let mut wrapper = Cleanup(wrapper);
        arrived_receive
            .recv_timeout(Duration::from_secs(15))
            .unwrap();
        assert!(wrapper.0.try_wait().unwrap().is_none());
        assert!(!marker.exists());
        // Signal the actual CLI while its request is pending. No arbitrary
        // sleep guesses when the broker or process has reached this boundary.
        assert_eq!(unsafe { libc::kill(wrapper.0.id() as i32, signal) }, 0);
        release_send.send(()).unwrap();
        let deadline = Instant::now() + Duration::from_secs(20);
        let status = loop {
            if let Some(status) = wrapper.0.try_wait().unwrap() {
                break status;
            }
            assert!(
                Instant::now() < deadline,
                "pending-grant cancellation deadline"
            );
            std::thread::sleep(Duration::from_millis(5));
        };
        use std::io::Seek;
        fn bytes(mut file: std::fs::File) -> Vec<u8> {
            file.rewind().unwrap();
            let mut bytes = Vec::new();
            file.read_to_end(&mut bytes).unwrap();
            bytes
        }
        let output = Output {
            status,
            stdout: bytes(stdout),
            stderr: bytes(stderr),
        };
        assert_exit(&output, 128 + signal);
        assert!(!marker.exists(), "cancelled wrapper started a child");
        // The peer records one start and exactly one end for the returned ID;
        // a successful local exit is insufficient without this broker evidence.
        assert_ended(&peer.finish());
    }
}
